"""Add projects and categories

Revision ID: 698170e0951a
Revises: a5963b9a3d37
Create Date: 2026-08-06 13:26:06.534383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698170e0951a'
down_revision: Union[str, Sequence[str], None] = 'a5963b9a3d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_ledger_projects_id', 'projects', ['project_id'], ['id'])
        batch_op.create_foreign_key('fk_ledger_categories_id', 'categories', ['category_id'], ['id'])
        # batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
