"""phase7_approval_audit_accountability

Revision ID: 982401215032
Revises: 698170e0951a
Create Date: 2026-08-08 12:35:59.009835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982401215032'
down_revision: Union[str, Sequence[str], None] = '698170e0951a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_number', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'VERIFIED', 'COMPLETED', 'VOIDED', 'REJECTED', name='transactionstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_requests_request_number'), ['request_number'], unique=True)

    op.create_table('approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('approver_id', sa.String(), nullable=False),
    sa.Column('approval_level', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'VERIFIED', 'COMPLETED', 'VOIDED', 'REJECTED', name='transactionstatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['request_id'], ['expense_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'VERIFIED', 'COMPLETED', 'VOIDED', 'REJECTED', name='transactionstatus'), server_default='COMPLETED', nullable=False))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions', sa.JSON(), server_default='[]', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('permissions')

    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('approvals')
    with op.batch_alter_table('expense_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_requests_request_number'))

    op.drop_table('expense_requests')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
