"""Add ledger models

Revision ID: a5963b9a3d37
Revises: af2c44bc7fc3
Create Date: 2026-08-06 13:08:39.086417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5963b9a3d37'
down_revision: Union[str, Sequence[str], None] = 'af2c44bc7fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('transaction_number', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('Income', 'Expense', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('entered_by', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transaction_number'), 'ledger', ['transaction_number'], unique=True)
    op.create_table('opening_balances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('financial_year', sa.String(), nullable=False),
    sa.Column('opening_balance', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opening_balances_financial_year'), 'opening_balances', ['financial_year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opening_balances_financial_year'), table_name='opening_balances')
    op.drop_table('opening_balances')
    op.drop_index(op.f('ix_ledger_transaction_number'), table_name='ledger')
    op.drop_table('ledger')
    # ### end Alembic commands ###
